name: Deployment
on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'src'
        destination-github-username: 'fake-orgn'
        destination-repository-name: 'new'
        user-email: tmohansk@gmail.com
